### PR TITLE
Remove top level 'query' key if exists

### LINKED ISSUE #251: TypeError: Cannot read property 'query_string' of undefined
will be triggered when rules does not contain `query` at first index

https://github.com/johnsusek/praeco/blob/master/src/store/config/index.js#L100

### PR DESCRIPTION
**Pull request by vtdat**
You'll be able to view multiple query as in https://github.com/Yelp/elastalert/issues/1468#issue-283664553

Array of filter represents as a string.

Resolves #251

### CODE REVIEW

**Comment by nsano-rururu** [comment]
@vtdat 

Thank you very much for this pull request!

**Comment by nsano-rururu** [comment]
@vtdat 

The graph is no longer displayed as shown below due to one of the changes requested by the pull request. When I changed all the contents of the source code that you changed in the local environment to the state before modification, the graph was displayed without any problem. After checking a little more, we plan to restore the changed contents to the source code before the change.

error

**Comment by nsano-rururu** [comment]
@vtdat 

I tried to release it, but the result was disappointing.

**Comment by vtdat** [comment]
> @vtdat
> 
> I tried to release it, but the result was disappointing.

k

**Pull request merged**
