### PR TITLE
Fixed the vue-at popup being missplaced.

### PR DESCRIPTION
**Pull request by SAM112000**
Made a change in the <style scope>, added a Deep Selector to adjust the position of the popup.
Deep Selector had to be used because the element is not in the code, it appears only when the popup is used after "%" is typed in the form. So for that reason the style of that element had to be changed through the parent element with Deep Selector.
MicrosoftTeams-image
MicrosoftTeams-image (1)
MicrosoftTeams-image (2)

### CODE REVIEW

**Comment by SAM112000** [comment]
Only added 4 lines of code on the line 207 of the ConfigAlertSubjectBody.vue file, I don't know why it shows so many changes.

**Comment by nsano-rururu** [comment]
I don't understand what I'm saying I don't understand by adding irrelevant changes. What are you talking about

**Review by nsano-rururu — CHANGES_REQUESTED** [review]
Please undo the parts that are not related to the correction.

**Comment by SAM112000** [comment]
@nsano-rururu  It should be fine now

**Review by SAM112000 — COMMENTED** [review]
Fix

**Comment by nsano-rururu** [comment]
There are still irrelevant fixes left.

**Review by SAM112000 — COMMENTED** [review]
Fixed the irrelevant changes.

**Comment by SAM112000** [comment]
Oh I see now. That was weird I am not sure why that happened. I fixed it now sorry for the troubles, didn't work much with github.
Now it should be all good! :)

**Review by nsano-rururu — APPROVED** [review]

**Pull request merged**
