### PR TITLE
added support for googleChat alerts

### PR DESCRIPTION
**Pull request by abhishek-rio**
let's add support for google chat alerts as well!

### CODE REVIEW

**Comment by nsano-rururu** [comment]
@abhishek-rio 

Thank you very much for this pull request!

**Comment by nsano-rururu** [comment]
@abhishek-rio

Is it correct to recognize that the alert notification to google chat has been confirmed?

**Comment by nsano-rururu** [comment]
There is no google chat icon,
Is the icon displayed?
https://fontawesome.com/icons?d=gallery&q=googlechat&s=solid&m=free

src/components/config/alert/ConfigAlert.vue

Line 258～260

```
        <template slot="label">
          <icon :icon="['fab', 'googlechat']" size="1x" /> GOOGLE CHAT
        </template>
```

It needs to be modified to the following contents.

```
        <template slot="label">
          GOOGLE CHAT
        </template>
```


Reference information

By the way, if the icon exists, it cannot be used in the program unless the icon used by the following source code is added.

src/contrib.js 
https://github.com/johnsusek/praeco/blob/master/src/contrib.js#L24
https://github.com/johnsusek/praeco/blob/master/src/contrib.js#L36

**Comment by nsano-rururu** [comment]
@abhishek-rio 

Did you forget to implement the following settings?
I'm not blaming you.
I wondered if there was any reason why I didn't use it normally

googlechat_header_subtitle
googlechat_header_image
googlechat_footer_kibanalink
https://elastalert.readthedocs.io/en/latest/ruletypes.html#googlechat

**Comment by abhishek-rio** [comment]
> @abhishek-rio
> 
> There is no google chat icon,
> Is the icon displayed?
> https://fontawesome.com/icons?d=gallery&q=googlechat&s=solid&m=free
> 
> src/components/config/alert/ConfigAlert.vue
> 
> Line 258～260
> 
> ```
>         <template slot="label">
>           <icon :icon="['fab', 'googlechat']" size="1x" /> GOOGLE CHAT
>         </template>
> ```
> 
> It needs to be modified to the following contents.
> 
> ```
>         <template slot="label">
>           GOOGLE CHAT
>         </template>
> ```
> 
> Reference information
> 
> By the way, if the icon exists, it cannot be used in the program unless the icon used by the following source code is added.
> 
> src/contrib.js
> https://github.com/johnsusek/praeco/blob/master/src/contrib.js#L24
> https://github.com/johnsusek/praeco/blob/master/src/contrib.js#L36

fixed

**Comment by abhishek-rio** [comment]
> @abhishek-rio
> 
> Did you forget to implement the following settings?
> I'm not blaming you.
> I wondered if there was any reason why I didn't use it normally
> 
> googlechat_header_subtitle
> googlechat_header_image
> googlechat_footer_kibanalink
> https://elastalert.readthedocs.io/en/latest/ruletypes.html#googlechat

I haven't seen many people using these settings.

**Comment by nsano-rururu** [comment]
@abhishek-rio 

Are the following three settings required for alert notification?
Since the ElastAlert documentation only requires "googlechat_webhook_url"
https://elastalert.readthedocs.io/en/latest/ruletypes.html#googlechat

googlechat_format
googlechat_header_title
googlechat_header_subtitle

If it is not required, delete "required" as shown below.

**src/components/config/alert/ConfigAlert.vue**

Line 266

```
<praeco-form-item label="GoogleChat Format" prop="googleChatFormat" required>
↓
<praeco-form-item label="GoogleChat Format" prop="googleChatFormat">
```

Line 270

```
<praeco-form-item label="GoogleChat Header Title" prop="googleChatHeaderTitle" required>
↓
<praeco-form-item label="GoogleChat Header Title" prop="googleChatHeaderTitle">
```

**Comment by nsano-rururu** [comment]
@abhishek-rio 

Does googlechat_format specify a value of either basic or card? In that case, wouldn't it be better to use radio buttons as shown below?

**src/components/config/alert/ConfigAlert.vue**

```
<el-form-item label="GoogleChat Format" prop="googleChatFormat" required>
  <el-radio-group v-model="googleChatFormat" :disabled="viewOnly">
    <el-radio id="googleChatFormatBasic" label="basic" border>
      basic
    </el-radio>
    <el-radio id="googleChatFormatCard" label="card" border>
      card
    </el-radio>
  </el-radio-group>
</el-form-item>
```

**Comment by nsano-rururu** [comment]
@abhishek-rio 

If it does not correspond, I will respond after importing it, so please reply whether it corresponds or not

**Comment by nsano-rururu** [comment]
@abhishek-rio

I'm planning to capture and release this weekend, is there any problem?

**Comment by abhishek-rio** [comment]
> @abhishek-rio
> 
> I'm planning to capture and release this weekend, is there any problem?

No, got caught up in some other task. Will make the changes asap

**Comment by nsano-rururu** [comment]
@abhishek-rio

understood. You don't have to hurry, so take action when your work is calm.

**Comment by abhishek-rio** [comment]
> @abhishek-rio
> 
> Does googlechat_format specify a value of either basic or card? In that case, wouldn't it be better to use radio buttons as shown below?
> 
> **src/components/config/alert/ConfigAlert.vue**
> 
> ```
> <el-form-item label="GoogleChat Format" prop="googleChatFormat" required>
>   <el-radio-group v-model="googleChatFormat" :disabled="viewOnly">
>     <el-radio id="googleChatFormatBasic" label="basic" border>
>       basic
>     </el-radio>
>     <el-radio id="googleChatFormatCard" label="card" border>
>       card
>     </el-radio>
>   </el-radio-group>
> </el-form-item>
> ```

fixed

**Comment by abhishek-rio** [comment]
> @abhishek-rio
> 
> understood. You don't have to hurry, so take action when your work is calm.

I have made the suggested changes, please review

**Pull request merged**
