### PR TITLE
Fix JIRA integration

### PR DESCRIPTION
**Pull request by osherdp**
The old code has bugs in it.
I hope it fixes all issues for now. I want to see how easy it will be to add auto-completion in the JIRA fields.

### CODE REVIEW

**Comment by johnsusek** [comment]
Thx I will take a look tomorrow. The CI fail is probably not your fault :)

**Comment by osherdp** [comment]
@johnsusek anything new?

**Comment by johnsusek** [comment]
Hi just wanted to give an update since you've been so patient! Basically I am waiting until next week when I can make some changes the build/deploy integration. Thanks!

**Comment by osherdp** [comment]
anything new on that?

**Comment by johnsusek** [comment]
@osherdp Merged, docker images will still have to be published

**Pull request merged**
